name: Code Formatting Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  format-code:
    name: Check Code Formatting with Black
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Black
        run: pip install black

      - name: Run Black Formatting Check
        run: black --check .
